☕ 서울 강동구 오플비 추가 size/M
utilForever/awesome-cafe pull request #15
Opened 2022-03-27 07:08 UTC by Ha-Young

☕ 추천해요

2022-03-27 14:00 UTC, utilForever requested changes
기여해주셔서 감사합니다. 수정할 부분이 있으니 확인 부탁드립니다.

2022-03-27 14:00 UTC, utilForever commented on README.md
> +- [라이선스](#라이선스)
이 부분 `*`을 `-`으로 바꾼 이유가 있으신가요?
특별한 이유가 없다면, 롤백 부탁드립니다.

2022-03-27 14:00 UTC, utilForever commented on README.md
> +  - 월,화,목,금 : 09:00 ~ 20:00
띄어쓰기 부탁드립니다.
```suggestion
  - 월, 화, 목, 금 : 09:00 ~ 20:00
```

2022-03-27 14:00 UTC, utilForever commented on README.md
> +  - 수 : 09:00 ~ 19:00
요일을 서로 바꾸면 좋겠네요.
```suggestion
  - 수 : 09:00 ~ 19:00
  - 토 : 09:30 ~ 20:00
```

2022-03-27 14:00 UTC, utilForever commented on README.md
> +  - 일 : 휴무
일요일 위치가 토요일 밑으로 가는 게 좋겠습니다.

2022-03-27 14:00 UTC, utilForever commented on README.md
> +  - 교회 1,2층을 카페로 만들었음
띄어쓰기 부탁드립니다.
```suggestion
  - 교회 1, 2층을 카페로 만들었음
```

2022-03-27 14:00 UTC, utilForever commented on README.md
> +  - 6인이상시 6인테이블, 회의실 이용가능
띄어쓰기 부탁드립니다.
```suggestion
  - 6인 이상 시 6인 테이블, 회의실 이용 가능
```

2022-04-08 02:04 UTC, ecpark-danbi commented on README.md
> +- [라이선스](#라이선스)
vscode에 내장된 markdown lint 가 저장할 때 자동으로 바꾸더라구요. 저도 롤백하느라 좀 애먹었습니다. vscode 셋팅에서 린트에 save on save 기능을 꺼주어야 합니다.

2022-10-09 15:49 UTC, Ha-Young commented
수정했습니다.
까먹고있었네요. 🙇‍♂️

2022-10-12 01:54 UTC, utilForever approved these changes
LGTM now! 기여해주셔서 감사합니다. 🙇

2022-10-12 01:54 UTC, merged