feat: ☕️카페드팽, 부산커피, 카페부케 추가
utilForever/awesome-cafe pull request #3
Opened 2022-03-10 07:00 UTC by zzzinho

#### [`카페 이름`](네이버 장소 링크)

- 위치
- 규모
- 운영 시간
  - 평일
  - 주말
- 혼잡도
  - 평일
  - 주말
- 가격대
- 책상 및 의자 특징
- 콘센트 유무
- 콘센트 개수
- 와이파이 유무
- 와이파이 속도
- 기타 특징

2022-03-10 11:32 UTC, utilForever requested changes
기여 감사합니다! 수정할 부분이 있어서 남겨뒀습니다.

2022-03-10 11:32 UTC, utilForever commented on README.md
> +- [라이선스](#라이선스)
여기 바꾸신 특별한 이유가 있나요?

2022-03-10 11:32 UTC, utilForever commented on README.md
> +- 규모 : 지하1층~2층
```suggestion
- 규모 : 지하 1층 ~ 2층
```

2022-03-10 11:32 UTC, utilForever commented on README.md
> +  - vip 카드 생성시 음료 5% 할인
```suggestion
  - VIP 카드 생성시 음료 5% 할인
```

2022-03-10 11:32 UTC, utilForever commented on README.md
> +  - 평일 점심 음료 20% 할인(~13:00)
```suggestion
  - 평일 점심 음료 20% 할인 (~13:00)
```

2022-03-10 11:32 UTC, utilForever commented on README.md
> +  - 음료/베이커리 서빙해주심
```suggestion
  - 음료/베이커리 서빙해 주심
```

2022-03-11 04:02 UTC, zzzinho commented on README.md
> +- [라이선스](#라이선스)
부산 부문에 목차를 추가하다가 실수로 수정 된 것 같습니다

2022-03-11 04:08 UTC, utilForever commented on README.md
> +- [라이선스](#라이선스)
아하, 그렇다면 목차만 추가해주시고 나머지는 롤백 부탁드립니다.

2022-03-11 04:17 UTC, closed without merging