카페얀(jyjy8940)
utilForever/awesome-cafe pull request #34
Opened 2023-06-09 23:13 UTC by jyjy8940

☕ 기여해주셔서 감사합니다! :)

2023-06-17 12:02 UTC, utilForever requested changes
기여해주셔서 감사합니다! 수정할 부분이 있어서 요청드립니다.

2023-06-17 12:02 UTC, utilForever commented on README.md
> +- - 3층 다인용 책상과 스터디룸에서 개발하기 좋음.
-가 2번 들어간 줄이 일부 있는데 수정 부탁드립니다.
```suggestion
- 위치 : 대구 달서구 달서대로109안길 16
- 규모 : 1층 로비, 2층, 3층
- 운영 시간
  - 평일 : 09:30-22:00
  - 주말 : 10:00-22:00
- 혼잡도
  - 평일 : 붐빔
  - 주말 : 보통
- 가격대
  - 음료 : 아메리카노 4,000원
  - 베이커리 : 3,500원 ~
- 책상 및 의자 특징
  - 2층 소파와 낮은 책상
  - 3층 둥근 1인 책상, 다인용 책상
- 콘센트 유무 : 유
- 콘센트 개수 : 2층 적음, 3층 많음
- 와이파이 유무 : 유
- 와이파이 속도 : 빠름
- 기타 특징
  - 와이파이 비번 없음
  - 아이스 아메리카노 샷 추가 가능
  - 말렌카 판매
  - 통유리창이고 앞에 숲 공원이 있어서 경치가 좋음
  - 스터디룸 있음
  - 2층과 3층의 분위기가 다름
  - 3층 다인용 책상과 스터디룸에서 개발하기 좋음
```

2023-07-21 06:20 UTC, jyjy8940 commented on README.md
> +- - 3층 다인용 책상과 스터디룸에서 개발하기 좋음.
수정했습니다!

2023-07-24 02:22 UTC, utilForever approved these changes
수정 확인했습니다. 기여해주셔서 감사합니다! ☕

2023-07-24 02:22 UTC, merged