add: 서울 카페 추가
utilForever/awesome-cafe pull request #39
Opened 2024-04-30 02:01 UTC by givvemee

서울 가장 마지막 항목 구디 할리스 추가합니당. :)

☕ 기여해주셔서 감사합니다! :)

2024-05-20 14:57 UTC, utilForever requested changes
기여해주셔서 감사합니다! 수정할 부분이 있어서 요청드립니다.

2024-05-20 14:57 UTC, utilForever commented on README.md
> +  - 케바케이지만 주말 오후에도 빈 좌석이 최소 1개씩 유지되고 있음
표준어로 변경해주세요.
```suggestion
  - 때에 따라 다르지만 주말 오후에도 빈 좌석이 최소 1개씩 유지되고 있음
```

2024-05-20 14:57 UTC, utilForever commented on README.md
> +  - 구디 2번 출구 도보 5분 이내
표준어로 변경해주세요.
```suggestion
  - 구로디지털단지역 2번 출구 도보 5분 이내
```

2024-05-20 14:57 UTC, utilForever commented on README.md
> +  - 긴 테이블 좌석은 현재 콘센트가 막혀 있는 관계로 최대 4인 팟이 좋아 보임
표준어로 변경해주세요.
```suggestion
  - 긴 테이블 좌석은 현재 콘센트가 막혀 있는 관계로 최대 4명이 모이는 게 좋아 보임
```

2024-05-21 04:00 UTC, givvemee commented on README.md
> +  - 긴 테이블 좌석은 현재 콘센트가 막혀 있는 관계로 최대 4인 팟이 좋아 보임
@utilForever 확인 감사합니다. XD

2024-05-21 07:19 UTC, utilForever approved these changes
수정 확인했습니다. 감사합니다! 🍡

2024-05-21 07:19 UTC, merged