☕ 서울 북쌔즈 카페 추가
utilForever/awesome-cafe pull request #41
Opened 2024-08-14 12:24 UTC by silverstar0727

☕ 기여해주셔서 감사합니다! :)

2024-09-02 04:17 UTC, utilForever requested changes
기여해주셔서 감사합니다! 수정할 부분이 있어서 요청드립니다.

2024-09-02 04:17 UTC, utilForever commented on README.md
> +- 규모 : 1.5층(2층 좌석 적음)
```suggestion
- 규모 : 1.5층 (2층 좌석 적음)
```

2024-09-02 04:17 UTC, utilForever commented on README.md
> +  - 토요일. 일요일 : 09:30 ~ 20:30
```suggestion
  - 토요일, 일요일 : 09:30 ~ 20:30
```

2024-09-02 04:17 UTC, utilForever commented on README.md
> +  - 빵 메뉴로는 '퀸 아망'이 맛있음.
```suggestion
  - 책이 다수 전시되어 있어 도서관 같은 분위기가 남
  - 2층은 개인 좌석이 대다수이고, 공부하는 분위기가 조성됨
  - 빵 메뉴로는 '퀸 아망'이 맛있음
```

2024-09-02 06:16 UTC, silverstar0727 commented
반영했습니다!! :)

2024-09-19 15:33 UTC, utilForever approved these changes
확인이 많이 늦었습니다. 고맙습니다!

2024-09-19 15:33 UTC, merged